### PR TITLE
write basic archive bot and clone methods

### LINKED ISSUE #1: Software Heritage Action
I'd love an action that could be placed into a repo of scientific software to trigger the software heritage save API: https://archive.softwareheritage.org/api/1/origin/save/doc/

Ideally this could happen on commits to either any branch or a specific branch.

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #1 

- get organization from github actions context automatically, or provide manually in `.env` for running locally
- function to fetch all repos (and wiki repos) from an organization
- function to submit repos to Software Heritage with smart info and error messages, and retry timeouts
- function to generate and run a script for cloning all the repos
- create github action to run the `archive` script ~weekly

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Notes to reviewers:

Originally I set the timeout based on what SH returns when throttling. E.g., when I got "Request throttled. Expected to be available again in 2340 seconds", I would set a timer for 2340 seconds. But in my testing, I observed that the rate limit often seems to get cleared much sooner than that. As such, I just used a simple exponentially growing delay.

I did try out https://github.com/clockfort/GitHub-Backup but found that it simply didn't work. I ran into several errors, including frequent rate limits that would make cloning our whole organization impractical.

**Comment by vincerubinetti** [comment]
The folks at Software Heritage say that we shouldn't be hitting rate limiting with the authorization token.

I believe I'm passing the token correctly. The [`options` I'm passing to node fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options):

```javascript
{
  method: 'POST',
  headers: {
    Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSl...'
  }
}
```

As of this morning, I'm getting a little further into the list of repos before getting throttled, but still < 50% of the way through. I've removed the line archiving wikis for now which will help. The script will work, it will just take a few hours to run because each time we get throttled, we need to wait about an hour.

**Comment by vincerubinetti** [comment]
Per a recent email with Software Heritage:

> you will be happy to know that the rate limit for API access for registered users has been raised a few hours ago to 1200/hour (ten times the previous value), so you should definitely not have any more issues.

I'm still running into throttling though. Perhaps the problem will resolve itself if we give it a day. It seems like using an auth token did increase our limit, but it took a day. Perhaps it will take another day for the new limit to take effect for some reason...

@dongbohu do you have any ideas about this.

**Comment by dongbohu** [comment]
I have no idea. Let's wait for another day and see whether it will be effective.

**Comment by vincerubinetti** [comment]
Well as of today it's still being rate limited after around 100 repos, but that's okay. It will just take longer to run with all the timeouts. But it'll be running in the background only a few times a month so it shouldn't matter.

@dongbohu If you can spot any errors in my code where I'm passing the token, let me know. Otherwise I think I'm doing it correctly and something is wrong or wrongly documented on the Software Heritage side. Going to merge.

**Pull request merged**
